# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tictactoe.proto',
  package='tictactoe',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftictactoe.proto\x12\ttictactoe\"\xd7\x01\n\x10TicTacToeMessage\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.tictactoe.MessageType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12%\n\x06player\x18\x03 \x01(\x0e\x32\x15.tictactoe.PlayerType\x12\x10\n\x08win_type\x18\x04 \x01(\x05\x12\x14\n\x0cis_your_turn\x18\x05 \x01(\x08\x12,\n\x0cplayer_shape\x18\x06 \x01(\x0e\x32\x16.tictactoe.PlayerShape\x12\x0f\n\x07version\x18\x07 \x01(\t*.\n\x0bPlayerShape\x12\x11\n\rUNKNOWN_SHAPE\x10\x00\x12\x05\n\x01X\x10\x01\x12\x05\n\x01O\x10\x02*\x87\x01\n\x0bMessageType\x12\t\n\x05START\x10\x00\x12\x08\n\x04\x43HAT\x10\x01\x12\x08\n\x04MOVE\x10\x02\x12\x11\n\rRESET_REQUEST\x10\x03\x12\x16\n\x12RESET_CONFIRMATION\x10\x04\x12\x0b\n\x07MESSAGE\x10\x05\x12\x0e\n\nPLAY_AGAIN\x10\x06\x12\x11\n\rVERSION_CHECK\x10\x07*<\n\nPlayerType\x12\x12\n\x0eUNKNOWN_PLAYER\x10\x00\x12\x0c\n\x08PLAYER_1\x10\x01\x12\x0c\n\x08PLAYER_2\x10\x02\x62\x06proto3'
)

_PLAYERSHAPE = _descriptor.EnumDescriptor(
  name='PlayerShape',
  full_name='tictactoe.PlayerShape',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SHAPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='X', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='O', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=248,
  serialized_end=294,
)
_sym_db.RegisterEnumDescriptor(_PLAYERSHAPE)

PlayerShape = enum_type_wrapper.EnumTypeWrapper(_PLAYERSHAPE)
_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='tictactoe.MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHAT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESET_REQUEST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESET_CONFIRMATION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAY_AGAIN', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERSION_CHECK', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=297,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_PLAYERTYPE = _descriptor.EnumDescriptor(
  name='PlayerType',
  full_name='tictactoe.PlayerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_PLAYER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=434,
  serialized_end=494,
)
_sym_db.RegisterEnumDescriptor(_PLAYERTYPE)

PlayerType = enum_type_wrapper.EnumTypeWrapper(_PLAYERTYPE)
UNKNOWN_SHAPE = 0
X = 1
O = 2
START = 0
CHAT = 1
MOVE = 2
RESET_REQUEST = 3
RESET_CONFIRMATION = 4
MESSAGE = 5
PLAY_AGAIN = 6
VERSION_CHECK = 7
UNKNOWN_PLAYER = 0
PLAYER_1 = 1
PLAYER_2 = 2



_TICTACTOEMESSAGE = _descriptor.Descriptor(
  name='TicTacToeMessage',
  full_name='tictactoe.TicTacToeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tictactoe.TicTacToeMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='tictactoe.TicTacToeMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player', full_name='tictactoe.TicTacToeMessage.player', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='win_type', full_name='tictactoe.TicTacToeMessage.win_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_your_turn', full_name='tictactoe.TicTacToeMessage.is_your_turn', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_shape', full_name='tictactoe.TicTacToeMessage.player_shape', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='tictactoe.TicTacToeMessage.version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=246,
)

_TICTACTOEMESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
_TICTACTOEMESSAGE.fields_by_name['player'].enum_type = _PLAYERTYPE
_TICTACTOEMESSAGE.fields_by_name['player_shape'].enum_type = _PLAYERSHAPE
DESCRIPTOR.message_types_by_name['TicTacToeMessage'] = _TICTACTOEMESSAGE
DESCRIPTOR.enum_types_by_name['PlayerShape'] = _PLAYERSHAPE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
DESCRIPTOR.enum_types_by_name['PlayerType'] = _PLAYERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TicTacToeMessage = _reflection.GeneratedProtocolMessageType('TicTacToeMessage', (_message.Message,), {
  'DESCRIPTOR' : _TICTACTOEMESSAGE,
  '__module__' : 'tictactoe_pb2'
  # @@protoc_insertion_point(class_scope:tictactoe.TicTacToeMessage)
  })
_sym_db.RegisterMessage(TicTacToeMessage)


# @@protoc_insertion_point(module_scope)
